using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.CardPools;
using MegaCrit.Sts2.Core.Saves.Runs;

namespace StS2AP.Models
{
    /// <summary>
    /// Represents a Curse from a Death Link event.
    /// </summary>
    public sealed class DeathLinkCurse : CardModel
    {
        /// <summary>
        /// A serializable message representing the DeathLink event that caused this Curse to be generated.
        /// This will be used in the card's description.
        /// </summary>
        [SavedProperty]
        public string DeathMessage { get; private set; } = string.Empty;

        public DeathLinkCurse()
            : base(-1, CardType.Curse, CardRarity.Curse, TargetType.None)
        {
        }

        /// <summary>
        /// Can't be upgraded - it's a curse!
        /// </summary>
        public override int MaxUpgradeLevel => 0;

        /// <summary>
        /// Re-routes the path for the card's art to the `.ctex` generated by the build process, 
        /// as opposed to the default "look it up in an atlas" behavior.
        /// 
        /// The name looks funky, but this is the file name generated based on the path of the project, 
        /// it's defined in `ap-curse.png.import`, and it seems to be stable.
        /// 
        /// I'm open to changing how we do this in the future though.
        /// </summary>
        public override string PortraitPath => "res://.godot/imported/ap-curse.png-cbe6b83a033a53839cc218aaaa971726.ctex";

        /// <summary>
        /// By setting this flag to false, it prevents this curse from being randomly generated by events like 
        /// "Add a random Curse to your deck" or "Upgrade a random card in your deck".
        /// 
        /// I noticed this when looking at the Curse of the Bell's code, which had this flag yet also was included in the
        /// `CurseCardPool`, which made me think it prevents it from being randomly added outside it's random use case.
        /// </summary>
        public override bool CanBeGeneratedByModifiers => false;

        /// <summary>
        /// This places the Curse in the Curse Card Pool, which I didn't want to do but we have to apparently, 
        /// otherwise it won't show up in the game at all.
        /// 
        /// Good news is, the flag above prevents it from being shuffled into "random curse" events like "The Decider"
        /// </summary>
        public override CardPoolModel Pool => ModelDb.CardPool<CurseCardPool>();

        /// <summary>
        /// The Keywords for this card.
        /// We want it to be Unplayable so that the player can't do anything with it, and Eternal so that it can't be removed.
        /// </summary>
        public override IEnumerable<CardKeyword> CanonicalKeywords
            => new[] { CardKeyword.Unplayable, CardKeyword.Eternal };

        /// <summary>
        /// Writes the Death Message to the Card, after the card has been cloned (becomes mutable) from the database version.
        /// </summary>
        protected override void AfterCloned()
        {
            base.AfterCloned();
            if (ArchipelagoClient.LastDeathLinkMessage != null)
                DeathMessage = ArchipelagoClient.LastDeathLinkMessage;
        }

        /// <summary>
        /// Applies the Death Message to the Card
        /// </summary>
        protected override void AddExtraArgsToDescription(LocString description)
        {
            description.Add("death_message", DeathMessage);
        }
    }
}