/**
 * @file Serializes compiled Archipelago options into a readable YAML representation.
 *
 * This service sits after wizard compilation and validation. It knows nothing about
 * questions or player intent and must only receive compiled values plus validated
 * document metadata. The guided flow uses a deliberately small recursive serializer
 * suitable for generated scalars, lists, and nested mappings such as
 * `advanced_characters`, then wraps those settings in Archipelago's game block.
 */

import type { OptionValue } from "../generated/optionCatalog";
import { validateWizardPlayerName } from "../wizard/validation/validateWizardMetadata";

/** Stable description embedded in every generated wizard document. */
export const WIZARD_YAML_DESCRIPTION =
  "YAML generated by the StS 2 Online YAML Builder.";

/** Archipelago game identifier used by both metadata and the option mapping. */
export const WIZARD_GAME_NAME = "Slay the Spire II";

/**
 * Formats a primitive option value as a YAML-safe scalar.
 *
 * @param value - Boolean, number, or string value to serialize.
 * @returns YAML-safe scalar text; strings use JSON quoting, which YAML accepts.
 */
function scalar(value: boolean | number | string): string {
  // Quote strings to preserve empty strings and characters significant to YAML.
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

/**
 * Appends one keyed option value with YAML block indentation.
 *
 * @param lines - Mutable output lines being assembled by the public serializer.
 * @param key - Mapping key to write at the current indentation level.
 * @param value - Generated scalar, list, or nested mapping value to serialize.
 * @param indentation - Number of spaces preceding the mapping key.
 * @param quoteKey - Whether the key is dynamic data and must be JSON/YAML quoted.
 * @returns Nothing; appends a complete YAML representation to `lines`.
 * @remarks JSON string quoting is valid YAML and safely preserves modded character IDs.
 */
function appendValue(
  lines: string[],
  key: string,
  value: unknown,
  indentation: number,
  quoteKey: boolean,
): void {
  // Top-level option keys are generated identifiers; nested character IDs are data.
  const prefix = " ".repeat(indentation);
  const serializedKey = quoteKey ? JSON.stringify(key) : key;

  if (Array.isArray(value)) {
    // Preserve the distinction between an empty YAML list and an unspecified/null value.
    if (!value.length) {
      lines.push(`${prefix}${serializedKey}: []`);
      return;
    }

    lines.push(`${prefix}${serializedKey}:`);

    for (const entry of value) {
      appendSequenceEntry(lines, entry, indentation + 2);
    }

    return;
  }

  if (value !== null && typeof value === "object") {
    // Preserve empty dictionaries explicitly for ignored or optional option payloads.
    const entries = Object.entries(value);

    if (!entries.length) {
      lines.push(`${prefix}${serializedKey}: {}`);
      return;
    }

    lines.push(`${prefix}${serializedKey}:`);

    // Recurse so advanced character mappings remain readable and structurally exact.
    for (const [childKey, childValue] of entries) {
      appendValue(lines, childKey, childValue, indentation + 2, true);
    }

    return;
  }

  // Primitive options fit on the same line as their key.
  lines.push(
    `${prefix}${serializedKey}: ${scalar(value as boolean | number | string)}`,
  );
}

/**
 * Appends one entry of a YAML block sequence at the given indentation.
 *
 * @param lines - Mutable output lines being assembled by the serializer.
 * @param entry - Scalar or mapping sequence entry to serialize.
 * @param indentation - Number of spaces preceding the `- ` marker.
 * @returns Nothing; appends the entry's complete YAML representation to `lines`.
 * @remarks Mapping entries such as `WAX_RELIC` bonus items emit their first key on
 * the dash line and remaining keys on following lines, matching hand-written YAML.
 */
function appendSequenceEntry(
  lines: string[],
  entry: unknown,
  indentation: number,
): void {
  const prefix = " ".repeat(indentation);

  if (entry !== null && typeof entry === "object" && !Array.isArray(entry)) {
    const childEntries = Object.entries(entry);

    // An empty mapping inside a sequence still needs an explicit representation.
    if (!childEntries.length) {
      lines.push(`${prefix}- {}`);
      return;
    }

    // The first key shares the dash line so the entry reads as one nested block.
    const [firstKey, firstValue] = childEntries[0]!;

    if (firstValue !== null && typeof firstValue === "object") {
      lines.push(`${prefix}- ${firstKey}:`);
      appendNested(lines, firstValue, indentation + 4);
    } else {
      lines.push(
        `${prefix}- ${firstKey}: ${scalar(firstValue as boolean | number | string)}`,
      );
    }

    // Subsequent keys align under the first key, two spaces past the dash.
    for (const [childKey, childValue] of childEntries.slice(1)) {
      appendValue(lines, childKey, childValue, indentation + 2, false);
    }

    return;
  }

  if (Array.isArray(entry)) {
    // A nested list as a direct sequence entry is emitted as a child sequence.
    if (!entry.length) {
      lines.push(`${prefix}- []`);
      return;
    }

    lines.push(`${prefix}-`);
    for (const child of entry) {
      appendSequenceEntry(lines, child, indentation + 2);
    }

    return;
  }

  // Scalar entries such as character names serialize inline after the dash.
  lines.push(`${prefix}- ${scalar(entry as boolean | number | string)}`);
}

/**
 * Appends the value of a mapping key that opened on a parent line.
 *
 * @param lines - Mutable output lines being assembled by the serializer.
 * @param value - List or mapping value belonging to the already-written key.
 * @param indentation - Number of spaces for the value's children.
 * @returns Nothing; appends the nested block representation to `lines`.
 */
function appendNested(
  lines: string[],
  value: unknown,
  indentation: number,
): void {
  const prefix = " ".repeat(indentation);

  if (Array.isArray(value)) {
    // Empty nested lists stay inline-style on their own line for clarity.
    if (!value.length) {
      lines.push(`${prefix}[]`);
      return;
    }

    for (const entry of value) {
      appendSequenceEntry(lines, entry, indentation);
    }

    return;
  }

  // Nested mappings recurse with data keys quoted for safety.
  for (const [childKey, childValue] of Object.entries(
    value as Record<string, unknown>,
  )) {
    appendValue(lines, childKey, childValue, indentation, false);
  }
}

/**
 * Serializes compiled options as deterministic, human-readable YAML.
 *
 * @param options - Ordered compiled option entries to serialize.
 * @returns YAML text ending with one newline.
 * @remarks Call this after compilation. This lightweight serializer supports the value
 * shapes in the generated catalog but is not intended as a general-purpose YAML library.
 */
export function optionsToYaml(options: Record<string, OptionValue>): string {
  // Build line-by-line so arrays and dictionaries receive exact block indentation.
  const lines: string[] = [];

  for (const [key, value] of Object.entries(options)) {
    // Generated top-level keys are safe identifiers and do not require quotes.
    appendValue(lines, key, value, 0, false);
  }

  // POSIX-style trailing newlines make copied and downloaded YAML cleaner.
  return `${lines.join("\n")}\n`;
}

/**
 * Builds a complete Archipelago YAML document for the guided wizard.
 *
 * @param playerName - Player name entered in the persistent wizard header.
 * @param options - Ordered, compiled game options selected for guided output.
 * @returns Complete YAML with player metadata and an indented game option mapping.
 * @throws When the player name is invalid.
 * @remarks Preview, clipboard, and download callers must all consume this one result so
 * metadata and option serialization cannot diverge between delivery mechanisms.
 */
export function buildWizardYaml(
  playerName: string,
  options: Record<string, OptionValue>,
): string {
  // Normalize the only player-authored metadata value before writing any YAML.
  const normalizedPlayerName = validateWizardPlayerName(playerName);

  // Serialize generated options through the established recursive implementation.
  const serializedOptions = optionsToYaml(options).trimEnd().split("\n");
  const lines = [
    // Archipelago's player-name field is conventionally a readable plain YAML scalar.
    `name: ${normalizedPlayerName}`,
    `description: ${scalar(WIZARD_YAML_DESCRIPTION)}`,
    `game: ${scalar(WIZARD_GAME_NAME)}`,
    `${WIZARD_GAME_NAME}:`,
  ];

  // Archipelago expects every game option beneath the matching game-name key.
  for (const optionLine of serializedOptions) {
    lines.push(`  ${optionLine}`);
  }

  // Preserve the conventional trailing newline for previews and downloaded files.
  return `${lines.join("\n")}\n`;
}
