name: Validate Mod

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

# If someone pushes 3 commits rapidly, don't waste time finishing the obsolete builds for commits 1 and 2
concurrency:
  group: validate-mod-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  # Grab the StS2 Versions we want to validate against
  versions:
    uses: ./.github/workflows/get-sts2-versions.yml

  apworld:
    name: Build APWorld
    uses: ./.github/workflows/build-apworld.yml
    with:
      upload_artifact: false

  client:
    name: Build C# Client - StS2 v${{ matrix.sts2-version }}
    needs: versions

    strategy:
      fail-fast: false
      matrix:
        sts2-version: ${{ fromJSON(needs.versions.outputs.matrix) }}

    uses: ./.github/workflows/build-client.yml
    with:
      build_mode: CompileOnly
      sts2_api_compat: ${{ matrix.sts2-version }}
